Imports and Reading Data

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pylab as plt
import seaborn as sns
#plt.style.use('ggplot')
#pd.set_option('max_columns', 200)

In [3]:
ds0 = pd.read_csv('dataSets/mainDataSet/actors.csv')
ds1 = pd.read_csv('dataSets/mainDataSet/countries.csv')
ds2 = pd.read_csv('dataSets/mainDataSet/crew.csv')
ds3 = pd.read_csv('dataSets/mainDataSet/genres.csv')
ds4 = pd.read_csv('dataSets/mainDataSet/languages.csv')
ds5 = pd.read_csv('dataSets/mainDataSet/movies.csv')
ds6 = pd.read_csv('dataSets/mainDataSet/posters.csv')
ds7 = pd.read_csv('dataSets/mainDataSet/releases.csv')
ds8 = pd.read_csv('dataSets/mainDataSet/studios.csv')
ds9 = pd.read_csv('dataSets/mainDataSet/themes.csv')

In [4]:
ds0.head()

        id               name    role
0  1000001      Margot Robbie  Barbie
1  1000001       Ryan Gosling     Ken
2  1000001    America Ferrera  Gloria
3  1000001  Ariana Greenblatt   Sasha
4  1000001           Issa Rae  Barbie

In [5]:
ds1.head()

        id      country
0  1000001           UK
1  1000001          USA
2  1000002  South Korea
3  1000003          USA
4  1000004      Germany

In [6]:
ds9.head()

        id                                              theme
0  1000001                   Humanity and the world around us
1  1000001                             Crude humor and satire
2  1000001                        Moving relationship stories
3  1000001     Emotional and captivating fantasy storytelling
4  1000001  Surreal and thought-provoking visions of life ...

Merging all Data-sets by id

In [7]:
# Unisci i primi due dataset
df = pd.merge(ds0, ds1, on='id', how='inner')

# Unisci il risultato con il terzo dataset
#df = pd.merge(df, ds3, on='id', how='inner')

# Continua fino a unire tutti i dataset
#df = pd.merge(df, ds4, on='id', how='inner')
#df = pd.merge(df, ds5, on='id', how='inner')
#df = pd.merge(df, ds6, on='id', how='inner')
#df = pd.merge(df, ds7, on='id', how='inner')
#df = pd.merge(df, ds8, on='id', how='inner')
#df = pd.merge(df, ds9, on='id', how='inner')
df.head(1000)

          id             name           role country
0    1000001    Margot Robbie         Barbie      UK
1    1000001    Margot Robbie         Barbie     USA
2    1000001     Ryan Gosling            Ken      UK
3    1000001     Ryan Gosling            Ken     USA
4    1000001  America Ferrera         Gloria      UK
..       ...              ...            ...     ...
995  1000006   Matthew Modine  Vannevar Bush      UK
996  1000006   Matthew Modine  Vannevar Bush     USA
997  1000006     Scott Grimes        Counsel      UK
998  1000006     Scott Grimes        Counsel     USA
999  1000006     Kurt Koehler  Thomas Morgan      UK

[1000 rows x 4 columns]

In [8]:
# Conta le righe con valori nulli nella colonna 'id'
#null_count = ds0['id'].isnull().sum()
#print(f"Numero di righe con 'id' nullo: {null_count}")
ds0.head()

        id               name    role
0  1000001      Margot Robbie  Barbie
1  1000001       Ryan Gosling     Ken
2  1000001    America Ferrera  Gloria
3  1000001  Ariana Greenblatt   Sasha
4  1000001           Issa Rae  Barbie

In [9]:
null_count = ds0['name'].isnull().sum()
print(f"Numero di righe con 'nome' nullo: {null_count}") #si possono togliere dal ds
# Filtra le righe dove il nome è nullo
righe_con_nome_nullo = ds0[ds0['name'].isnull()]

# Stampa le righe con nome nullo
print(righe_con_nome_nullo)
null_count = ds0['role'].isnull().sum()
print(f"Numero di righe con 'role' nullo: {null_count}") #troppe per essere tolte

Numero di righe con 'nome' nullo: 4
              id name            role
4145738  1443629  NaN             NaN
4281100  1469981  NaN            Self
4306960  1474958  NaN  Cinematography
5430275  1773264  NaN             NaN
Numero di righe con 'role' nullo: 1361559

In [10]:
df.isna().sum()

id               0
name             1
role       1219046
country          0
dtype: int64

In [11]:
ds1.isna().sum()

id         0
country    0
dtype: int64

In [12]:
ds2.isna().sum()

id      0
role    0
name    1
dtype: int64

In [13]:
ds3.isna().sum()

id       0
genre    0
dtype: int64

In [14]:
ds4.isna().sum()

id          0
type        0
language    0
dtype: int64

In [15]:
ds4.isna().sum()

id          0
type        0
language    0
dtype: int64

In [16]:
ds5.isna().sum()

id                  0
name               10
date            91913
tagline        802210
description    160812
minute         181570
rating         850598
dtype: int64

In [17]:
ds6.isna().sum()

id           0
link    180712
dtype: int64

In [18]:
ds7.isna().sum()

id              0
country         0
date            0
type            0
rating     998802
dtype: int64

In [19]:
ds8.isna().sum()

id         0
studio    10
dtype: int64

In [20]:
ds9.isna().sum()

id       0
theme    0
dtype: int64

In [21]:
df.tail(100)

              id             name                 role       country
5922828  1941506    Maxime Bonett               Alexia            UK
5922829  1941506      Adam Zellen            Dr. Ecorn            UK
5922830  1941506      Mike Kelson              Grandad            UK
5922831  1941510  Ethan Whitfield                 Cole  South Africa
5922832  1941510  Matthew D’Alton              Clayton  South Africa
...          ...              ...                  ...           ...
5922923  1941596          Marc Ma            Ba Cai/巴莱         China
5922924  1941596              线雨轩              Tata/塔塔         China
5922925  1941596     Jiang Yixuan  Zuo Yila（Zoila）/佐伊拉         China
5922926  1941597   Hiroshi Mikami                  NaN         Japan
5922927  1941597    Keiko Oginome                  NaN         Japan

[100 rows x 4 columns]

In [22]:
df['country'].value_counts()

country
USA                                             1733672
France                                           364979
UK                                               361978
Japan                                            344345
Germany                                          339263
                                                 ...
French Southern Territories                           2
South Georgia and the South Sandwich Islands          1
Cocos (Keeling) Islands                               1
Pitcairn                                              1
Heard Island and McDonald Islands                     1
Name: count, Length: 245, dtype: int64

In [24]:
# Conta il numero di paesi unici
df['country'].nunique()

245

In [29]:
conteggio_paesi = df['country'].value_counts()

# Converti la serie in un DataFrame e resetta l'indice
conteggio_paesi_df = conteggio_paesi.reset_index()

# Rinomina le colonne
conteggio_paesi_df.columns = ['country', 'Film Count']

# Aggiungi un numero di riga
conteggio_paesi_df['Row Number'] = range(1, len(conteggio_paesi_df) + 1)

# Stampa il risultato
#print(conteggio_paesi_df)
conteggio_paesi_df

                                          country  Film Count  Row Number
0                                             USA     1733672           1
1                                          France      364979           2
2                                              UK      361978           3
3                                           Japan      344345           4
4                                         Germany      339263           5
..                                            ...         ...         ...
240                   French Southern Territories           2         241
241  South Georgia and the South Sandwich Islands           1         242
242                       Cocos (Keeling) Islands           1         243
243                                      Pitcairn           1         244
244             Heard Island and McDonald Islands           1         245

[245 rows x 3 columns]

Country
USA                                             1
France                                          1
UK                                              1
Japan                                           1
Germany                                         1
                                               ..
French Southern Territories                     1
South Georgia and the South Sandwich Islands    1
Cocos (Keeling) Islands                         1
Pitcairn                                        1
Heard Island and McDonald Islands               1
Name: count, Length: 245, dtype: int64