Imports and Reading Data

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pylab as plt
import seaborn as sns
#plt.style.use('ggplot')
#pd.set_option('max_columns', 200)

In [14]:
ds0 = pd.read_csv('dataSets/mainDataSet/actors.csv')
ds1 = pd.read_csv('dataSets/mainDataSet/countries.csv')
ds2 = pd.read_csv('dataSets/mainDataSet/crew.csv')
ds3 = pd.read_csv('dataSets/mainDataSet/genres.csv')
ds4 = pd.read_csv('dataSets/mainDataSet/languages.csv')
ds5 = pd.read_csv('dataSets/mainDataSet/movies.csv')
ds6 = pd.read_csv('dataSets/mainDataSet/posters.csv')
ds7 = pd.read_csv('dataSets/mainDataSet/releases.csv')
ds8 = pd.read_csv('dataSets/mainDataSet/studios.csv')
ds9 = pd.read_csv('dataSets/mainDataSet/themes.csv')

In [16]:
ds0.head()

        id      country
0  1000001           UK
1  1000001          USA
2  1000002  South Korea
3  1000003          USA
4  1000004      Germany

In [17]:
ds1.head()

        id      country
0  1000001           UK
1  1000001          USA
2  1000002  South Korea
3  1000003          USA
4  1000004      Germany

In [18]:
ds9.head()

        id                                              theme
0  1000001                   Humanity and the world around us
1  1000001                             Crude humor and satire
2  1000001                        Moving relationship stories
3  1000001     Emotional and captivating fantasy storytelling
4  1000001  Surreal and thought-provoking visions of life ...

Merging all Data-sets by id

In [20]:
# Unisci i primi due dataset
df = pd.merge(ds0, ds1, on='id', how='inner')

# Unisci il risultato con il terzo dataset
df = pd.merge(df, ds3, on='id', how='inner')

# Continua fino a unire tutti i dataset
df = pd.merge(df, ds4, on='id', how='inner')
df = pd.merge(df, ds5, on='id', how='inner')
df = pd.merge(df, ds6, on='id', how='inner')
df = pd.merge(df, ds7, on='id', how='inner')
df = pd.merge(df, ds8, on='id', how='inner')
df = pd.merge(df, ds9, on='id', how='inner')

MemoryError: Unable to allocate 4.01 GiB for an array with shape (4, 134694953) and data type object

In [19]:
df.head()

        id               name    role
0  1000001      Margot Robbie  Barbie
1  1000001       Ryan Gosling     Ken
2  1000001    America Ferrera  Gloria
3  1000001  Ariana Greenblatt   Sasha
4  1000001           Issa Rae  Barbie

In [7]:
df.columns

Index(['id', 'name', 'role'], dtype='object')

In [8]:
df.dtypes

id       int64
name    object
role    object
dtype: object

(4720183, 3)